{
 "title": "Statistc",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Стоимость показов по кампаниям за день",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    campaign_id, \n    date, \n    SUM(cost) AS total_impression_cost \nFROM unique_impressions \nGROUP BY campaign_id, date \nORDER BY date ASC; -- Сортировка по возрастанию даты"
    }
   ]
  },
  {
   "title": "Стоимость кликов по кампаниям за день",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \n    campaign_id, \n    date, \n    SUM(cost) AS total_click_cost \nFROM unique_clicks \nGROUP BY campaign_id, date \nORDER BY date ASC; -- Сортировка по возрастанию даты"
    }
   ]
  },
  {
   "title": "Общее количество показов по кампаниям за день",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \n    campaign_id, \n    date, \n    COUNT(*) AS impression_count \nFROM unique_impressions \nGROUP BY campaign_id, date \nORDER BY date ASC;"
    }
   ]
  },
  {
   "title": "Общее количество кликов по кампаниям за день",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT \n    campaign_id, \n    date, \n    COUNT(*) AS click_count \nFROM unique_clicks \nGROUP BY campaign_id, date \nORDER BY date ASC; -- Сортировка по возрастанию даты"
    }
   ]
  },
  {
   "title": "Общее количество кликов на рекламу по дням",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT date, COUNT(*) AS value\nFROM unique_clicks\nGROUP BY date\nORDER BY date"
    }
   ]
  }
 ]
}