"""update unique clicks table

Revision ID: 77d5353216a0
Revises: ba5252e39b85
Create Date: 2025-02-13 19:19:53.614084

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "77d5353216a0"
down_revision: Union[str, None] = "ba5252e39b85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("unique_clicks", sa.Column("campaign_id", sa.Uuid(), nullable=False))
    op.drop_constraint(
        "unique_clicks_unique_ad_id_fkey", "unique_clicks", type_="foreignkey"
    )
    op.create_foreign_key(None, "unique_clicks", "campaigns", ["campaign_id"], ["id"])
    op.drop_column("unique_clicks", "unique_ad_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "unique_clicks",
        sa.Column("unique_ad_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "unique_clicks", type_="foreignkey")
    op.create_foreign_key(
        "unique_clicks_unique_ad_id_fkey",
        "unique_clicks",
        "campaigns",
        ["unique_ad_id"],
        ["id"],
    )
    op.drop_column("unique_clicks", "campaign_id")
    # ### end Alembic commands ###
