"""add cost field to uniques tables;

Revision ID: b17409dfbf29
Revises: a55efe22153e
Create Date: 2025-02-14 16:17:09.255382

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b17409dfbf29"
down_revision: Union[str, None] = "a55efe22153e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("impressions")
    op.drop_table("clicks")
    op.add_column("unique_clicks", sa.Column("cost", sa.Float(), nullable=False))
    op.add_column("unique_impressions", sa.Column("cost", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("unique_impressions", "cost")
    op.drop_column("unique_clicks", "cost")
    op.create_table(
        "clicks",
        sa.Column("campaign_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "cost",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("date", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("client_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"], ["campaigns.id"], name="clicks_campaign_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["client_id"], ["clients.id"], name="clicks_client_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="clicks_pkey"),
    )
    op.create_table(
        "impressions",
        sa.Column("campaign_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "cost",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("date", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name="impressions_campaign_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="impressions_pkey"),
    )
    # ### end Alembic commands ###
