"""update clicks table

Revision ID: c269f7b9f407
Revises: 695ff2140d3b
Create Date: 2025-02-13 12:18:05.059720

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c269f7b9f407"
down_revision: Union[str, None] = "695ff2140d3b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clicks", sa.Column("client_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(None, "clicks", "clients", ["client_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "clicks", type_="foreignkey")
    op.drop_column("clicks", "client_id")
    # ### end Alembic commands ###
