"""add files to campaigns

Revision ID: 88fc5e0b7ac1
Revises: b17409dfbf29
Create Date: 2025-02-15 18:05:31.951884

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "88fc5e0b7ac1"
down_revision: Union[str, None] = "b17409dfbf29"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "campaigns",
        sa.Column("files", postgresql.JSON(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("campaigns", "files")
    # ### end Alembic commands ###
