"""add ml scores table

Revision ID: 101688d708a6
Revises: 2b012f8bcfbf
Create Date: 2025-02-13 00:43:05.566940

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "101688d708a6"
down_revision: Union[str, None] = "2b012f8bcfbf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mlscores",
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("advertiser_id", sa.Uuid(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["advertiser_id"],
            ["advertisers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_id", "advertiser_id", name="uix_client_advertiser"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mlscores")
    # ### end Alembic commands ###
