"""update unique clicks and unique impressions tables

Revision ID: ba5252e39b85
Revises: c269f7b9f407
Create Date: 2025-02-13 18:24:29.383271

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ba5252e39b85"
down_revision: Union[str, None] = "c269f7b9f407"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "unique_clicks",
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("unique_ad_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unique_ad_id"],
            ["campaigns.id"],
        ),
        sa.PrimaryKeyConstraint("client_id", "unique_ad_id", "date", "id"),
    )
    op.create_table(
        "unique_impressions",
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("client_id", "campaign_id", "date", "id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("unique_impressions")
    op.drop_table("unique_clicks")
    # ### end Alembic commands ###
