"""add is_deleted column

Revision ID: 537c9e0a1795
Revises: 88fc5e0b7ac1
Create Date: 2025-02-22 02:24:54.975977

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "537c9e0a1795"
down_revision: Union[str, None] = "88fc5e0b7ac1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "campaigns", sa.Column("is_deleted", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("campaigns", "is_deleted")
    # ### end Alembic commands ###
