"""add campaigns and targetings tables

Revision ID: 2b012f8bcfbf
Revises: f6049490c2c3
Create Date: 2025-02-12 18:31:20.879099

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2b012f8bcfbf"
down_revision: Union[str, None] = "f6049490c2c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campaigns",
        sa.Column("advertiser_id", sa.Uuid(), nullable=False),
        sa.Column("impressions_limit", sa.Integer(), nullable=False),
        sa.Column("clicks_limit", sa.Integer(), nullable=False),
        sa.Column("cost_per_impression", sa.Float(), nullable=False),
        sa.Column("cost_per_click", sa.Float(), nullable=False),
        sa.Column("ad_title", sa.String(), nullable=False),
        sa.Column("ad_text", sa.String(), nullable=False),
        sa.Column("start_date", sa.Integer(), nullable=False),
        sa.Column("end_date", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["advertiser_id"],
            ["advertisers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "targetings",
        sa.Column(
            "gender",
            sa.Enum("MALE", "FEMALE", "ALL", name="extendedgenderenum"),
            nullable=False,
        ),
        sa.Column("age_from", sa.Integer(), nullable=False),
        sa.Column("age_to", sa.Integer(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("campaign_id"),
    )
    op.alter_column(
        "clients",
        "gender",
        existing_type=postgresql.ENUM("MALE", "FEMALE", name="genderenum"),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "clients",
        "gender",
        existing_type=postgresql.ENUM("MALE", "FEMALE", name="genderenum"),
        nullable=True,
    )
    op.drop_table("targetings")
    op.drop_table("campaigns")
    # ### end Alembic commands ###
