apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres
    uid: bed1513lwpiwwb
    url: db:5432
    database: backend-advertising-platform-postgres
    user: postgres
    secureJsonData:
      password: "password"
    jsonData:
      sslMode: disable
    editable: true
    isDefault: true